### ISSUE TITLE
Ability to resize viewport from 0 to 100%

### ISSUE THREAD

**Issue by zchtodd** [PhotonDesigner/photon-designer#5]
Nice to have:  It's possible to resize the viewport using the drag handle, but it seems to be limited.  It would be nice to be able to have a greater range of widths using the viewport drag handle, to very quickly see how the page would reflow.

**Comment by tomdekan** [comment]
Good suggestion. Much nicer without the restriction. Done.



https://github.com/PhotonDesigner/photon-designer/assets/125155375/6fd90c3c-05d8-47a8-8eed-912cdda3dbda
